apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL25hdmFuZWV0aGhpbm9kMTg6bmF2YW5lZXRodW5uaUBjbHVzdGVyMC1zaGFyZC0wMC0wMC52eGM5OS5tb25nb2RiLm5ldDoyNzAxNyxjbHVzdGVyMC1zaGFyZC0wMC0wMS52eGM5OS5tb25nb2RiLm5ldDoyNzAxNyxjbHVzdGVyMC1zaGFyZC0wMC0wMi52eGM5OS5tb25nb2RiLm5ldDoyNzAxNy9DaGF0P3NzbD10cnVlJnJlcGxpY2FTZXQ9YXRsYXMtbjFraDhiLXNoYXJkLTAmYXV0aFNvdXJjZT1hZG1pbiZyZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==


