apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  VITE_STRIPE_KEY: cGtfdGVzdF81MVFJNXA5QlRMMWQweE5vV1B4UjZXZXV2Njk4c1RPQ2ExaGRjVTBjdVlCRkpEQ1dwNU9UU3hWdGVOUGRzY2VIVkFkNGM4YmczRXpxMVdkQkYwU2VrR2xYbTAwSVFFbHJiSkk=
  VITE_GOOGLE_CLIENT_ID: MjI1MjA0MjUwNzYyLTZyYmllaDhoODltcGs1MGJzNWl2dGsydGprc3E1czBtMi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
