apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL25hdmFuZWV0aHZpbm9kMTg6bmF2YW5lZXRodW5uaUBjbHVzdGVyMC1zaGFyZC0wMC0wMC52eGM5OS5tb25nb2RiLm5ldDoyNzAxNyxjbHVzdGVyMC1zaGFyZC0wMC0wMS52eGM5OS5tb25nb2RiLm5ldDoyNzAxNyxjbHVzdGVyMC1zaGFyZC0wMC0wMi52eGM5OS5tb25nb2RiLm5ldDoyNzAxNy9QYXltZW50P3NzbD10cnVlJnJlcGxpY2FTZXQ9YXRsYXMtbjFraDhiLXNoYXJkLTAmYXV0aFNvdXJjZT1hZG1pbiZyZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVFJNXA5QlRMMWQweE5vV2daM1pEU0U0MXJqMXlQeFlPVFRrdEMyR0E3VUs2OThlQ1ByVTVyRDR5QTJGejdwdnJaZXVXY1Z3NTg3bmlIQlVWQ2FFdTZ2WTAwRkF3NVFYT2Y=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfMzZLYU5lMVJOQ3RnMnc2YXdrMUlHWTlVOW1wNUxOaWw=
  FRONTEND_URL: aHR0cHM6Ly9lZHVjb3JlLmxpdmUv

