apiVersion: apps/v1
kind: Deployment
metadata:
  name: educore-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: navaneethvinod/educore-auth-service:latest
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: MONGO_URI
        - name: REDIS_URL
          value: redis://redis-svc:6379
        - name: JWT_AUTHSECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_AUTHSECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_REFRESH_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: GOOGLE_CLIENT_ID
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 3001
    targetPort: 3001
