apiVersion: apps/v1
kind: Deployment
metadata:
  name: educore-chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: navaneethvinod/educore-chat-service:latest
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: chat-secret
              key: MONGO_URI
      
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: chat-svc
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
  - name: chat
    protocol: TCP
    port: 3004
    targetPort: 3004