apiVersion: apps/v1
kind: Deployment
metadata:
  name: educore-course-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: course
        image: navaneethvinod/educore-course-service:latest
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: MONGO_URI
        - name: AWS_S3_REGION
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: AWS_S3_REGION
        - name: AWS_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: AWS_S3_ACCESS_KEY
        - name: AWS_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: AWS_S3_SECRET_KEY
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: AWS_S3_BUCKET_NAME
        - name: AWS_S3_EXPIRY_TIME
          valueFrom:
            secretKeyRef:
              name: course-secret
              key: AWS_S3_EXPIRY_TIME
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 3003

---
apiVersion: v1  
kind: Service
metadata:
  name: course-svc
spec:
  type: ClusterIP
  selector:
    app: course
  ports:
  - name: course
    protocol: TCP
    port: 3003
    targetPort: 3003
