apiVersion: apps/v1
kind: Deployment
metadata:
  name: educore-payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: navaneethvinod/educore-payment-service:latest
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: MONGO_URI
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: STRIPE_WEBHOOK_SECRET
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: FRONTEND_URL
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - name: payment
    protocol: TCP
    port: 3005
    targetPort: 3005
