openapi: 3.0.0
info:
  title: Educore API Gateway
  description: API Gateway for Educore application, routing requests to various services
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local API Gateway

paths:
  /api/students/signup:
    post:
      summary: Route to Student Service Sign-Up
      description: Route requests to the student service for user sign-up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                phone:
                  type: string
                  example: 9072263325
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  userId:
                    type: string
                    example: 1234567890
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input data

  /api/auth/signin:
    post:
      summary: Route to Student Service Sign-In
      description: Route requests to the student service for user sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User authenticated successfully
                  token:
                    type: string
                    example: jwt-token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password

  /api/tutors/signup:
    post:
      summary: Route to Tutor Service Sign-Up
      description: Route requests to the tutor service for tutor sign-up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                phone:
                  type: string
                  example: 9072263325
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '201':
          description: Tutor created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tutor created successfully
                  userId:
                    type: string
                    example: 1234567890
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input data

  /api/tutors/signin:
    post:
      summary: Route to Tutor Service Sign-In
      description: Route requests to the tutor service for tutor sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '200':
          description: Tutor authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tutor authenticated successfully
                  token:
                    type: string
                    example: jwt-token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password

  /api/admin/signin:
    post:
      summary: Route to Admin Service Sign-In
      description: Route requests to the admin service for admin sign-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: admin@example.com
                password:
                  type: string
                  format: password
                  example: adminpassword
      responses:
        '200':
          description: Admin authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin authenticated successfully
                  token:
                    type: string
                    example: jwt-token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message
