name: deploy-auth

on: 
  push: 
    branches: 
       - main
    paths:
       - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v2
      - run: cd auth-service && docker build -t navaneethvinod/educore-auth-service .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push navaneethvinod/educore-auth-service:latest
