name: deploy-manifest
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Save Kubernetes config
        run: doctl kubernetes cluster kubeconfig save k8s-1-31-1-do-5-blr1-1734852479838

      - name: Restart Kubernetes deployment
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s/stateless &&  kubectl apply -f infra/k8s/secrets  && kubectl apply -f infra/k8s/prod
